name: Generate registry

on:
  workflow_dispatch:

jobs:
  generate-registry:
    runs-on: ubuntu-latest
    environment: Deployment

    env:
      AWS_DEFAULT_REGION: auto
      R2_ENDPOINT_URL: https://5f0d4105431f10a4af1e1f0266f26a97.r2.cloudflarestorage.com
      R2_BUCKET: registry-useflows-com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate registry.json
        run: node .github/scripts/generate-registry.js

      - name: Sync icons to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FLOWS_REGISTRY_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FLOWS_REGISTRY_R2_SECRET_ACCESS_KEY }}
        run: |
          # Sync only changed/new icons to R2
          aws s3 sync apps/ "s3://${R2_BUCKET}/core/apps/" \
            --endpoint-url "${R2_ENDPOINT_URL}" \
            --exclude "*" \
            --include "*.svg" \
            --include "*.png" \
            --size-only

      - name: Upload registry.json to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FLOWS_REGISTRY_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FLOWS_REGISTRY_R2_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp registry.json "s3://${R2_BUCKET}/core/registry.json" \
            --endpoint-url "${R2_ENDPOINT_URL}" \
            --content-type "application/json"
