# This workflow is not meant to be run directly.
# It is called by app repos to upload app versions.
# It is triggered by the `workflow_call` event.
name: Upload app version

on:
  workflow_call:

jobs:
  deploy:
    name: Deploy to R2
    runs-on: ubuntu-latest
    environment: Deployment
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Bundle
        run: npm run bundle

      - name: Extract app name and version
        id: extract
        run: |
          RAW_APP_NAME=$(basename $PWD)
          APP_NAME=${RAW_APP_NAME#flows-app-}
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate upload path
        run: |
          # Ensure apps can only upload to their designated paths
          REPO_NAME="${{ github.repository }}"
          if [[ "$REPO_NAME" =~ flows-app- ]]; then
            EXPECTED_APP_NAME=${REPO_NAME#*/flows-app-}
            if [[ "${{ steps.extract.outputs.app_name }}" != "$EXPECTED_APP_NAME" ]]; then
              echo "Error: App name mismatch. Expected: $EXPECTED_APP_NAME, got: ${{ steps.extract.outputs.app_name }}"
              exit 1
            fi
          elif [[ "$REPO_NAME" =~ -registry$ ]]; then
            echo "Registry repo detected, allowing upload"
          else
            echo "Error: Unknown repository type"
            exit 1
          fi

      - name: Create tarball and calculate checksum
        id: package
        run: |
          CHECKSUM=$(sha256sum bundle.tar.gz | cut -d' ' -f1)
          echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT

      - name: Upload to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.FLOWS_REGISTRY_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.FLOWS_REGISTRY_R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          R2_BUCKET: registry-useflows-com
          R2_ENDPOINT_URL: https://5f0d4105431f10a4af1e1f0266f26a97.r2.cloudflarestorage.com
        run: |
          aws s3 cp bundle.tar.gz s3://${R2_BUCKET}/core/apps/${{ steps.extract.outputs.app_name }}/versions/${{ steps.extract.outputs.version }}.tar.gz \
            --endpoint-url ${R2_ENDPOINT_URL} \
            --metadata sha256=${{ steps.package.outputs.checksum }}
